# Generated by Django 4.2 on 2024-04-18 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0006_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
